/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/Demo/Demo.vue')['default']
    Error: typeof import('./src/components/Error/src/Error.vue')['default']
    Indexs: typeof import('./src/components/MonacoEditor/indexs.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor/index.vue')['default']
    PreviewCode: typeof import('./src/components/PreviewCode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TinymceEditor: typeof import('./src/components/TinymceEditor/index.vue')['default']
  }
}
